name: Feature request
description: Suggest an idea or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem does this feature solve?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed solution
      description: How should it work?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Alternatives
      description: Any alternative solutions or workarounds?
